"use client";

import { useState, useCallback } from "react";
import { useWalletClient, usePublicClient } from "wagmi";
import { decodeEventLog, toHex } from "viem";
import ritualRouletteAbi from "@/abi/RitualRoulette";
import { buildSpinLlmInput } from "@/lib/ritualLlm";
import { rouletteContractAddress } from "@/config/contract";
import { ritualChain } from "@/config/wagmi";

export type SpinTxStatus =
  | "idle"
  | "building"      // encoding LLM prompt
  | "signing"       // waiting for wallet signature
  | "pending"       // tx broadcast, waiting for confirmation
  | "confirmed"     // tx confirmed, parsing event
  | "success"       // got AI message
  | "error";

export interface SpinTxResult {
  status: SpinTxStatus;
  txHash?: `0x${string}`;
  aiMessage?: string;   // decoded AI guide from contract event
  error?: string;
  run: (dappName: string) => Promise<void>;
  reset: () => void;
}

/**
 * Manages the on-chain spin transaction flow:
 *  1. Encode LLM prompt via buildSpinLlmInput
 *  2. Ask wallet to sign & send submitDailySpin()
 *  3. Wait for confirmation
 *  4. Read RouletteSpun event → decode AI bytes → UTF-8 string
 *
 * Falls back to a mock "bot" message when no contract address is configured
 * (so the UI works in dev/sandbox mode without a live deployment).
 */
export function useSpinTransaction(): SpinTxResult {
  const [status, setStatus] = useState<SpinTxStatus>("idle");
  const [txHash, setTxHash] = useState<`0x${string}` | undefined>();
  const [aiMessage, setAiMessage] = useState<string | undefined>();
  const [error, setError] = useState<string | undefined>();

  const { data: walletClient } = useWalletClient({ chainId: ritualChain.id });
  const publicClient = usePublicClient({ chainId: ritualChain.id });

  const reset = useCallback(() => {
    setStatus("idle");
    setTxHash(undefined);
    setAiMessage(undefined);
    setError(undefined);
  }, []);

  const run = useCallback(async (dappName: string) => {
    reset();

    // ── SANDBOX MODE ── No contract deployed yet → simulate bot after 3s
    if (!rouletteContractAddress) {
      setStatus("signing");
      await new Promise((r) => setTimeout(r, 800));
      setStatus("pending");
      await new Promise((r) => setTimeout(r, 1400));
      setStatus("confirmed");
      await new Promise((r) => setTimeout(r, 600));
      setAiMessage(
        `🤖 Ritual Agent deployed!\n\n` +
        `You just discovered **${dappName}** on the Ritual Ecosystem.\n\n` +
        `Here's your step-by-step guide:\n` +
        `1. Visit the dApp link and connect your wallet (Ritual Testnet).\n` +
        `2. Find the main action button — usually "Mint", "Try", or "Submit".\n` +
        `3. Confirm the transaction in MetaMask.\n` +
        `4. Share your result on X with #RitualChain to earn community points!\n\n` +
        `_This guidance was generated by an AI agent running inside Ritual TEE. Every spin = one agent deploy._`
      );
      setStatus("success");
      return;
    }

    // ── LIVE MODE ── Contract is deployed, do real on-chain tx
    try {
      if (!walletClient || !publicClient) {
        throw new Error("Wallet not connected.");
      }

      // Step 1: Encode the LLM prompt
      setStatus("building");
      const llmInput = buildSpinLlmInput(dappName);

      // Step 2: Sign & send tx
      setStatus("signing");
      const hash = await walletClient.writeContract({
        address: rouletteContractAddress,
        abi: ritualRouletteAbi,
        functionName: "submitDailySpin",
        args: [dappName, llmInput as `0x${string}`],
        chain: ritualChain,
      });
      setTxHash(hash);

      // Step 3: Wait for receipt
      setStatus("pending");
      const receipt = await publicClient.waitForTransactionReceipt({ hash });

      setStatus("confirmed");

      // Step 4: Parse RouletteSpun event from logs
      let decoded: string | undefined;
      for (const log of receipt.logs) {
        try {
          const evt = decodeEventLog({
            abi: ritualRouletteAbi,
            data: log.data,
            topics: log.topics,
            eventName: "RouletteSpun",
          });
          // aiGeneratedTweet is bytes → decode as UTF-8
          const raw = evt.args.aiGeneratedTweet as `0x${string}`;
          decoded = new TextDecoder().decode(
            Buffer.from(raw.replace(/^0x/, ""), "hex")
          );
          break;
        } catch {
          // Not the right log, continue
        }
      }

      setAiMessage(
        decoded && decoded.trim().length > 0
          ? `🤖 Ritual Agent says:\n\n${decoded.trim()}`
          : `🤖 Ritual Agent deployed for **${dappName}**!\n\nTransaction confirmed on Ritual Chain. Your agent is live — go explore the dApp and complete the interaction!`
      );
      setStatus("success");
    } catch (e: unknown) {
      const msg =
        (e as { shortMessage?: string; message?: string }).shortMessage ??
        (e as Error).message ??
        "Transaction failed.";
      setError(msg);
      setStatus("error");
    }
  }, [walletClient, publicClient, reset]);

  return { status, txHash, aiMessage, error, run, reset };
}
